### ISSUE TITLE
Messenger Bot instances with facebook-messenger

### ISSUE THREAD

**Issue by Fredis** [jgorset/facebook-messenger#235]
Hi guys,

Above all, thank you for your gem which works good for the moment :)!

I have a question regarding the messenger bot and here is the situation... My team and myself managed to create the bot in a specific facebook page (private) where only all admins/developers can reach for the moment. The application is not yet activated, we're presently testing it.

My question is related to the instance of the bot: when we test it, it seems that there is only one instance of the bot which is created... I explain myself :
- the first admin asks something to the bot, the bot gives an answer
- the second admin asks something to the bot, the bot is continuing the first conversation created by the first admin

Is this behavior normal? I mean because we're all working as "admins/developers" of the bot for the same page, so we manage only one conversation... Or do I have to think about another solution where the method "Bot.on" could be a kind of Object (with several instances)?

Best regards,
Fred.

**Comment by cfurrow** [comment]
The bot does not really have a concept of how many conversations it knows about. Facebook will send all webhooks (message, read, postback, etc) to your web server, and it would be up to your code to handle the incoming response.

Is it possible that your server is not responding asynchronously? For instance, a message to your bot is coming into your service, and you are not passing the response off to some asynchronous code (such as sidekiq, resque, etc)? In that case, if you are responding synchronously inside your app, perhaps that is why?

Otherwise, there is no reason that your bot cannot handle multiple webhooks coming into your system at once, as long as you have multiple apps/threads/whatever listening to those incoming requests.
